peg/toml: Change some rule names to shut up GCC
It only complains about nan but true and false are known names too,
so let's change them as well since we are already here...

peg/toml.c:139:13: warning: conflicting types for built-in function 'nan'; expected 'double(const char *)' [-Wbuiltin-declaration-mismatch]
  139 | static RULE(nan);
      |             ^~~